# Generated by Django 3.0.2 on 2020-01-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20200104_2145"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="ip_address",
            field=models.GenericIPAddressField(default="0.0.0.0", verbose_name="IP주소"),
            preserve_default=False,
        ),
    ]
