# Generated by Django 3.0.2 on 2020-01-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="slack_channel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
