# Generated by Django 3.0.2 on 2020-09-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20200115_0120"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="vacation_days",
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
