# Generated by Django 3.0.2 on 2021-07-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20200903_1357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="total_days",
            field=models.FloatField(default=15.0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="used_days",
            field=models.FloatField(default=0.0),
        ),
    ]
