# Generated by Django 3.0.2 on 2021-07-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20210701_1548"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="sick_days",
            field=models.FloatField(default=0.0),
        ),
    ]
