# Generated by Django 3.0.2 on 2021-07-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_profile_sick_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="comp_days",
            field=models.FloatField(default=0.0),
        ),
    ]
