# Generated by Django 3.0.2 on 2021-07-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0003_auto_20210701_1509"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacation",
            name="half_day_off",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacation",
            name="one_fourth_day_off",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
