# Generated by Django 3.0.2 on 2021-07-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0004_auto_20210701_1820"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacation",
            name="end_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vacation",
            name="start_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
