# Generated by Django 3.0.2 on 2021-07-02 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0005_auto_20210701_1829"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacation",
            old_name="end_at",
            new_name="day_off_end_at",
        ),
        migrations.RenameField(
            model_name="vacation",
            old_name="start_at",
            new_name="day_off_start_at",
        ),
    ]
