# Generated by Django 3.0.2 on 2021-07-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0006_auto_20210702_0940"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacation",
            name="day_off_end_at",
        ),
        migrations.RemoveField(
            model_name="vacation",
            name="day_off_start_at",
        ),
        migrations.RemoveField(
            model_name="vacation",
            name="half_day_off",
        ),
        migrations.RemoveField(
            model_name="vacation",
            name="one_fourth_day_off",
        ),
        migrations.AddField(
            model_name="vacation",
            name="end_at",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="vacation",
            name="start_at",
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name="vacation",
            name="cat",
            field=models.CharField(
                choices=[("1", "연차/휴가"), ("2", "병가"), ("3", "반차"), ("4", "반반차")],
                default="1",
                max_length=1,
            ),
        ),
    ]
