# Generated by Django 3.0.2 on 2021-07-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation", "0007_auto_20210702_1424"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacation",
            name="cat",
            field=models.CharField(
                choices=[
                    ("1", "연차/휴가"),
                    ("2", "병가"),
                    ("3", "반차"),
                    ("4", "반반차"),
                    ("5", "대체휴가"),
                ],
                default="1",
                max_length=1,
            ),
        ),
    ]
